In [6]:
import numpy as np
import pandas as pd

In [11]:
# Cargar el archivo .npy
datos = np.load('proyecto_training_data.npy')
datosdf = pd.DataFrame(datos)

datosdf

0    1       2    3       4     5
0     208500.0  7.0   856.0  8.0  2003.0  65.0
1     181500.0  6.0  1262.0  6.0  1976.0  80.0
2     223500.0  7.0   920.0  6.0  2001.0  68.0
3     140000.0  7.0   961.0  7.0  1915.0  60.0
4     250000.0  8.0  1145.0  9.0  2000.0  84.0
...        ...  ...     ...  ...     ...   ...
1455  175000.0  6.0   953.0  7.0  1999.0  62.0
1456  210000.0  6.0  2073.0  7.0  1978.0  85.0
1457  266500.0  7.0  1188.0  9.0  1941.0  66.0
1458  142125.0  5.0  1078.0  5.0  1950.0  68.0
1459  147500.0  5.0  1256.0  6.0  1965.0  75.0

[1460 rows x 6 columns]

In [20]:
tamanio =len(datosdf) 
# Separar los datos entrenamiento (80%) 
tam_entrenamiento = int(0.8 * tamanio)

# validación y pruebas (20%)
tam_validacionpruebas = tamanio - tam_entrenamiento

datos_entrenamiento = datos[:tam_entrenamiento]
datos_validacionpruebas = datos[tam_entrenamiento:]

# Separar los datos de validación y pruebas en mitades iguales
tam_validacion = int(0.5 * len(datos_validacionpruebas))

datos_validacion = datos_validacionpruebas[:tam_validacion]
datos_pruebas = datos_validacionpruebas[tam_validacion:]

print("Tamaño Total")
print(tamanio)
print("Tamaño entrenamiento 80%")
print(tam_entrenamiento)
print("Tamaño validacion 10% y pruebas 10% (20%) ")
print(tam_validacionpruebas)
print("------------------------------")
print("Datos de entrenamiento:")
print(datos_entrenamiento)
print("\nDatos de validación:")
print(datos_validacion)
print("\nDatos de pruebas:")
print(datos_pruebas)

Tamaño Total
1460
Tamaño entrenamiento 80%
1168
Tamaño validacion 10% y pruebas 10% (20%) 
292
------------------------------
Datos de entrenamiento:
[[2.0850e+05 7.0000e+00 8.5600e+02 8.0000e+00 2.0030e+03 6.5000e+01]
 [1.8150e+05 6.0000e+00 1.2620e+03 6.0000e+00 1.9760e+03 8.0000e+01]
 [2.2350e+05 7.0000e+00 9.2000e+02 6.0000e+00 2.0010e+03 6.8000e+01]
 ...
 [2.3317e+05 7.0000e+00 1.5020e+03 7.0000e+00 2.0090e+03 7.9000e+01]
 [2.4535e+05 8.0000e+00 1.6940e+03 7.0000e+00 2.0080e+03 6.4000e+01]
 [1.7300e+05 6.0000e+00 9.5900e+02 7.0000e+00 2.0000e+03 5.8000e+01]]

Datos de validación:
[[2.35000e+05 6.00000e+00 1.23600e+03 7.00000e+00 1.93500e+03 1.20000e+02]
 [6.25000e+05 1.00000e+01 1.83100e+03 1.00000e+01 1.99500e+03 1.18000e+02]
 [1.71000e+05 6.00000e+00 1.11800e+03 6.00000e+00 1.97700e+03 7.60000e+01]
 [1.63000e+05 6.00000e+00 1.26100e+03 6.00000e+00 1.95800e+03 7.60000e+01]
 [1.71900e+05 7.00000e+00 6.25000e+02 5.00000e+00 2.00600e+03 3.50000e+01]
 [2.00500e+05 5.00000e+00 1.63600